### ISSUE TITLE
Remove trailing slash from employers breadcrumb URL

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2251]
The breadcrumb for Employment > Employers on the `apprenticeship`, `post-a-job`, and `support-veteran-employees` pages points to `/employment/employers/`.  On VEC, however, all the pages don't have a trailing slash on their URLs, so this is messing up the Google Analytics, as we now get requests to both `/employment/employers/` and `/employment/employers` (with and without the trailing slash).

@webinista do you know if there is there any way to make the breadcrumbs not have this trailing slash?

**Comment by emilyville** [comment]
I am not 100% certain of this, but I think there is also a way to make this not mess up GA. 

http://www.lunametrics.com/blog/2010/12/17/cleaning-urls-google-analytics/
http://www.trevorayers.com/top-5-google-analytics-filters/

It's not either/or - just a new option.

**Comment by ayaleloehr** [comment]
Great idea. That seems like a better way to solve this issue. Thank you @emilyville 

Closing this issue as this change isn't needed and @rickleegit is on editing this in Google Analytics (at some point...)

**Comment by ayaleloehr** [comment]
Per @joduinn 's suggestion, leaving open until resolved in Google Analytics.

**Comment by rickleegit** [comment]
We have a week of data supporting the successful update to GA that resolves the trailing slash/notrailing slash issue. It is configured to roll data up and display thusly: "/directory/". This is also documented in the vets.gov annotations, but please note that this does not fix all data retrospectively. Date ranges that include dates before 6 May 2016 will still render both views of the pages.
