### ISSUE TITLE
When accessing FL on IE there is a certification error. 

### ISSUE THREAD

**Issue by NatalieEMoore** [department-of-veterans-affairs/vets-website#3866]
Bug report from Jenny.  @jenny-h-l can you provide more detail or add a screen shot? 
 
When searching 22204 as zip code in IE (I will check in other browsers later, but wanted to get you this feedback ASAP) I get a security error that says “This certificate cannot be verified up to a trusted certification authority. Says it was issued to “api.mapbox.com”

**Comment by patrickvinograd** [comment]
Mapbox is the service used on the frontend to retrieve/display map tiles. Adding @bshyong although I may be able to help debug/diagnose if he is slammed.

**Comment by NatalieEMoore** [comment]
@bshyong can you tackle this or should @patrickvinograd help?

**Comment by bshyong** [comment]
@NatalieEMoore @patrickvinograd I'm not sure if there is anything we can do on our side—can we clear browser cache and try again?

I found this recent incident for MapBox which says that the certificate issue should be resolved http://status.mapbox.com/incidents/th5dqg3d62vf

**Comment by NatalieEMoore** [comment]
Okay I'll see if it happens to anyone else tomorrow and Jenny lmk if you still see it.

**Comment by bshyong** [comment]
cannot replicate—please ping if this is still happening

**Comment by jenny-h-l** [comment]
@bshyong cleared cache and still seeing the issue. are you testing with a VA computer using IE 11?

**Comment by NatalieEMoore** [comment]
make sure to update @jenny-h-l screenshots and more details as this is not happening for me and I'm also on IE 11.

**Comment by jenny-h-l** [comment]
see certificate screenshots  https://github.com/department-of-veterans-affairs/vets-website/files/582126/11-9-2016.5-59-48.PM.pdf 

https://github.com/department-of-veterans-affairs/vets-website/files/582125/11-9-2016.5-55-38.PM.pdf

**Comment by NatalieEMoore** [comment]
@jenny-h-l is the only one who can see it and we have tried on a few different computers so closing this for now unless someone else has the issue.
